name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        if: false # Remove this line to enable tests again
        env:
          PYTHONPATH: ${{ github.workspace }}/packages
          ENVIRONMENT: testing
        run: poetry run pytest

      - name: Check formatting
        run: poetry run black . --check
